export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CREATE_PROFILE = "CREATE_PROFILE";

export const ADDRESS_SUCCESS = "ADDRESS_SUCCESS";
export const ADDRESS_FAIL = "ADDRESS_FAIL";
export const EDUCATION_SUCCESSS = "EDUCATION_SUCCESSS";
export const EDUCATION_FAIL = "EDUCATION_FAIL";
export const GET_REPORT = "GET_REPORT";
export const GET_ALLREPORT = "GET_ALLREPORT";
export const GET_PRICING = "GET_PRICING";

//admin action
export const GET_CLIENT = "GET_CLIENT";
export const GET_VENDOR = "GET_VENDOR";
export const GET_OPERATION = "GET_OPERATION";
export const CREATE_PRICE = "CREATE_PRICE";
export const PRICE_ERROR = "PRICE_ERROR";
export const GET_PRICE = "GET_PRICE";

// Vendor Action
export const CREATEVENDOR_PROFILE = "CREATEVENDOR_PROFILE";
export const CREATEVENDOR_BUSINESS = "CREATEVENDOR_BUSINESS";
export const VENDORPROFILE_ERROR = "VENDORPROFILE_ERROR";


//operation Action
export const GET_EMPLOYEEUNDERVERIFICATION = "GET_EMPLOYEEUNDERVERIFICATION";
export const GET_EMPLOYEEASSIGNVENDOR = "GET_EMPLOYEEASSIGNVENDOR";
export const GET_EMPLOYEEAUDIT = "GET_EMPLOYEEAUDIT";
export const GET_VENDORBYSTATE = "GET_VENDORBYSTATE";
export const ASSIGN_VENDOR = "ASSIGN_VENDOR"


//new redux
export const ADD_PACKAGE = "ADD_PACKAGE"
export const GET_PACKAGE = "GET_PACKAGE"
export const ADD_CASE = "ADD_CASE"
export const GET_CASE = "GET_CASE"
export const GET_PACKAGEBYID = "GET_PACKAGEBYID"
export const GET_CASEBYID = "GET_CASEBYID"
export const GET_ADDRESSTL = "GET_ADDRESSTL"
export const GET_ADDRESSTEAM = "GET_ADDRESSTEAM"
export const GETS_CLIENT = "GETS_CLIENT"
